# Generated by Django 4.0.1 on 2022-01-21 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_question_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='kind',
            field=models.CharField(choices=[('t', 'Text'), ('m', 'Mcq')], default='t', max_length=1),
            preserve_default=False,
        ),
    ]
