# Generated by Django 4.0.1 on 2022-01-19 21:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contrib', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifaction',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
