# Generated by Django 4.0.1 on 2022-01-19 21:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contrib', '0003_notifaction_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifaction',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
